# StatefulSet for RabbitMQ
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq # Headless service for RabbitMQ
  replicas: 1 # Single replica
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management # RabbitMQ image with management UI
          ports:
            - containerPort: 5672 # AMQP protocol port
              name: rabbitmq-amqp
            - containerPort: 15672 # HTTP management UI port
              name: rabbitmq-http
          env: # Environment variables for RabbitMQ
            - name: RABBITMQ_DEFAULT_USER
              value: "username" # Default username
            - name: RABBITMQ_DEFAULT_PASS
              value: "password" # Default password
          resources: # Resource limits and requests
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts: # Mount configuration for RabbitMQ plugins
            - name: rabbitmq-enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
      volumes:
        - name: rabbitmq-enabled-plugins
          configMap:
            name: rabbitmq-enabled-plugins
            items:
              - key: rabbitmq_enabled_plugins
                path: enabled_plugins
---
# Service for RabbitMQ
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-amqp
      port: 5672
      targetPort: 5672
    - name: rabbitmq-http
      port: 15672
      targetPort: 15672
  type: ClusterIP
---